/**
 * Curated answer pool.
 *
 * The scraped dictionary is fine for validating a guess but unusable as an
 * answer source: it is full of abbreviations ("onom.", "bibl."), proper nouns
 * and words nobody has met ("betsi", "goral"). Losing a round to a word you
 * have never seen is the fastest way to kill a competitive room, so answers
 * are hand-picked and kept accented for the reveal — players type them without
 * accents and `normalize` bridges the two.
 */
export const ANSWERS: readonly string[] = [
  // A
  'ABRIL','ACASO','ACHAR','ÁCIDO','ADEUS','AFETO','AGORA','AGUDO','ÁGUIA','AINDA',
  'ALADO','ÁLBUM','ALGOZ','ALGUM','ALTAR','AMIGO','AMPLA','ANDAR','ANJOS','ANTES',
  'ANUAL','APOIO','AQUÉM','ARAME','AREIA','ARENA','ARROZ','ASILO','ASSIM','ASTRO',
  'ATRIZ','ATROZ','ÁUDIO','AUTOR','AVEIA','AVIÃO','AVISO','AZEDO',
  // B
  'BACIA','BAIXO','BALÃO','BALSA','BANCO','BANDA','BANDO','BANHO','BARBA','BARCO',
  'BARRA','BARRO','BASTA','BATOM','BEBER','BEIJO','BEIRA','BICHO','BISPO','BLOCO',
  'BLUSA','BOATE','BOLHA','BOLSA','BOMBA','BONDE','BORDA','BOTÃO','BRAÇO','BRASA',
  'BREVE','BRUTO','BRUXA','BURRO','BUSCA',
  // C
  'CABRA','CACAU','CACHO','CACTO','CAIXA','CALÇA','CALDA','CALMO','CALOR','CALVO',
  'CAMPO','CANAL','CANOA','CANTO','CAPAZ','CAPIM','CAPUZ','CARGA','CARGO','CARNE',
  'CARRO','CARTA','CASAL','CASCA','CASTA','CAUDA','CAUSA','CAVAR','CEDRO','CERCA',
  'CERCO','CERTO','CESTA','CETIM','CHAMA','CHAVE','CHEFE','CHEIO','CHUVA','CICLO',
  'CIFRA','CINCO','CINTO','CINZA','CIRCO','CISNE','CITAR','CIVIL','CLARO','CLIMA',
  'CLUBE','COBRA','COBRE','COICE','COISA','COLAR','COMER','COMUM','CONDE','CONTA',
  'CONTO','CÓPIA','CORAL','CORDA','COROA','CORPO','CORTE','CORVO','COSTA','COURO',
  'COUVE','CRAVO','CREDO','CREME','CRIAR','CRIME','CRISE','CRUEL','CULPA','CULTO',
  'CUNHA','CURSO','CURTO','CURVA','CUSTO',
  // D
  'DANÇA','DARDO','DELTA','DENTE','DESDE','DEUSA','DEVER','DIETA','DIGNO','DIQUE',
  'DISCO','DITAR','DÓCIL','DOIDO','DÓLAR','DOBRA','DOBRO','DORSO','DRAGA','DRAMA',
  'DROGA','DUELO','DUETO','DUPLA','DUPLO','DUQUE','DURAR',
  // E
  'EIXOS','ELITE','ENJOO','ENTRE','ENVIO','ÉPOCA','ERVAS','ESTAR','ÉTICO','ÊXITO',
  'EXAME','EXATO','ÊXODO','EXTRA',
  // F
  'FACÃO','FAIXA','FALAR','FALHA','FALSO','FARDA','FARSA','FATAL','FATIA','FATOR',
  'FAUNA','FAVOR','FAZER','FEBRE','FECHO','FEIRA','FEITO','FELIZ','FÊMUR','FENDA',
  'FERRO','FESTA','FEUDO','FIBRA','FICAR','FICHA','FILHA','FILHO','FILME','FINAL',
  'FIRMA','FIXAR','FLORA','FLUIR','FLUXO','FOCAR','FOGÃO','FOLGA','FOLHA','FONTE',
  'FORÇA','FORMA','FORNO','FORTE','FOSCO','FOSSA','FOSSO','FRACO','FRADE','FRASE',
  'FREIO','FRETE','FROTA','FRUTA','FRUTO','FUGIR','FUMAR','FUNIL','FURAR','FÚRIA',
  'FURTO','FUSÃO',
  // G
  'GAITA','GALHO','GANSO','GARÇA','GARFO','GARRA','GASTO','GELAR','GENRO','GENTE',
  'GESSO','GESTO','GIRAR','GLOBO','GOLPE','GORRO','GOSTO','GRAÇA','GRADE','GRAMA',
  'GRANA','GRATO','GREVE','GRIFO','GRIPE','GRITO','GRUPO','GUIAR',
  // H
  'HASTE','HAVER','HERÓI','HONRA','HORTA','HOTEL','HUMOR',
  // I
  'IDEIA','IDOSO','IGUAL','ÍMPAR','IMPOR','ÍNDIO','IRMÃO',
  // J
  'JARRA','JAULA','JEITO','JOGAR','JOIAS','JORRO','JOVEM','JULHO','JUNHO','JUNTA',
  'JUNTO','JURAR','JUROS','JUSTO',
  // L
  'LÁBIO','LAGOA','LÁPIS','LAPSO','LARGO','LASER','LATIM','LATIR','LAVAR','LAZER',
  'LEIGO','LEITE','LEITO','LENÇO','LENDA','LENHA','LENTO','LEQUE','LETRA','LEVAR',
  'LHAMA','LIBRA','LICOR','LÍDER','LIGAR','LIMÃO','LIMBO','LIMPO','LINCE','LINDA',
  'LINHA','LÍRIO','LISTA','LITRO','LIVRE','LIVRO','LOCAL','LOMBO','LONGE','LONGO',
  'LOUCO','LOURO','LOUSA','LUCRO','LUGAR','LUNAR','LUTAR',
  // M
  'MACHO','MACIO','MAGIA','MAGRO','MAIOR','MALHA','MAMÃE','MANGA','MANSO','MANTO',
  'MARCA','MARCO','MARTE','MASSA','MATAR','MÉDIA','MEDIR','MEIGA','MELÃO','MENTE',
  'MENOR','MENOS','MERDA','MESMO','METAL','METRO','MEXER','MICRO','MILHO','MINHA',
  'MIRAR','MISSA','MISTO','MOEDA','MOLDE','MOLHO','MONGE','MONTE','MORAL','MORAR',
  'MORNO','MORRO','MORTE','MOSCA','MOTOR','MOVER','MUDAR','MULTA','MUNDO','MUSEU',
  'MUSGO','MÚTUO',
  // N
  'NAÇÃO','NADAR','NAIPE','NARIZ','NATAL','NAVAL','NAVIO','NEGAR','NEGRO','NERVO',
  'NICHO','NEVAR','NÉVOA','NINHO','NÍVEL','NOBRE','NOITE','NOIVA','NORMA','NORTE',
  'NOSSO','NOTAR','NUVEM',
  // O
  'OÁSIS','OBTER','OESTE','OLHAR','OMBRO','ONTEM','OPÇÃO','ÓPERA','OPTAR','ORDEM',
  'ÓRGÃO','OSTRA','ÓTICA','ÓTIMO','OUSAR','OUVIR',
  // P
  'PACTO','PADRE','PAGAR','PAGÃO','PALCO','PALHA','PALMO','PANDA','PAPAI','PAPEL',
  'PARAR','PARDO','PARTO','PASSO','PASTA','PÁTIO','PAUSA','PAVOR','PECAR','PEDAL',
  'PEDIR','PEDRA','PEGAR','PEITO','PEIXE','PENTE','PERDA','PERNA','PERTO','PERUA',
  'PESAR','PESCA','PIANO','PILAR','PILHA','PINÇA','PINHO','PINTA','PINTO','PIRES',
  'PISTA','PLACA','PLANO','PLEBE','PLENO','PLUMA','POBRE','PODAR','PODER','PODRE',
  'POEMA','POETA','POLAR','POLVO','PONTA','PONTE','PONTO','PORÃO','PORCA','PORCO',
  'PORTA','PORTE','POSSE','POSTO','POUCO','POUSO','PRAÇA','PRAGA','PRAIA','PRATO',
  'PRAXE','PRAZO','PREÇO','PREGA','PREGO','PRESA','PRESO','PRETO','PRIMA','PRIMO',
  'PROSA','PROVA','PULGA','PULSO','PUNHO','PUXAR',
  // Q
  'QUASE','QUEDA','QUERO','QUILO','QUINA','QUOTA',
  // R
  'RADAR','RÁDIO','RAIVA','RALAR','RAMAL','RAMPA','RAPAZ','RASGO','RASPA','RAZÃO',
  'REFÉM','REGAR','REGRA','REINO','RELVA','REMAR','RENDA','REPOR','RESTO','RETER',
  'RETRO','REVÉS','REZAR','RIGOR','RIMAR','RINHA','RISCO','RITMO','RIVAL','ROCHA',
  'RODAR','ROJÃO','ROLAR','ROLHA','ROUBO','ROUPA','ROSCA','ROSTO','ROUCO','RUBRO',
  'RUELA','RUGIR','RUÍDO','RUÍNA','RUMOR','RURAL','RUSSO',
  // S
  'SABER','SÁBIO','SABOR','SAÍDA','SAÚDE','SACAR','SAFRA','SAGAZ','SALÃO','SALMO',
  'SALSA','SALTO','SALVA','SAMBA','SANAR','SANTO','SARAR','SAUNA','SECAR',
  'SELAR','SELIM','SELVA','SENHA','SENSO','SERRA','SERVO','SEXTA','SEXTO','SIGLA',
  'SIGNO','SINAL','SÍTIO','SOBRA','SOBRE','SOCAR','SÓCIO','SOGRA','SOGRO','SOLAR',
  'SOLDA','SONDA','SONHO','SOPRO','SORTE','SÓSIA','SÓTÃO','SUAVE','SUBIR','SUECO',
  'SUÍTE','SUJAR','SULCO','SUMIR','SUPER','SURDO','SURFE','SURTO','SUSTO',
  // T
  'TÁBUA','TALCO','TALHO','TANTO','TAPAR','TARDE','TARJA','TAROT','TECER','TECLA',
  'TEIMA','TELHA','TEMER','TEMPO','TENDA','TENRO','TENSO','TENTO','TERÇO','TERMO',
  'TERNO','TERRA','TESTE','TEXTO','TIGRE','TIMÃO','TINTA','TINTO','TOCAR',
  'TOCHA','TOMAR','TOMBO','TONEL','TOPAR','TOQUE','TORRE','TORSO','TORTA','TORTO',
  'TOTAL','TOUCA','TOURO','TRAGO','TRAJE','TRAMA','TRAPO','TRATO','TRAVA','TRAVE',
  'TRELA','TREVO','TREZE','TROCA','TROCO','TRONO','TROPA','TROTE','TRUFA','TUMBA',
  'TÚNEL','TURBO','TURCO','TURMA','TURNO','TUTOR',
  // U
  'ULTRA','ÚNICO','UNHAS','UNIÃO','UNIDO','UNTAR','URINA','USADO','USINA','ÚTERO',
  // V
  'VADIO','VAGÃO','VAGAR','VALOR','VALSA','VAPOR','VARAL','VARÃO','VASTO','VAZIO',
  'VEADO','VEDAR','VELAR','VELHO','VELOZ','VENDA','VENTO','VERÃO','VERBA','VERBO',
  'VERDE','VERME','VERSO','VESPA','VETOR','VIDRO','VIELA','VIGOR','VILÃO','VINCO',
  'VINDA','VINHO','VINIL','VINTE','VÍRUS','VISÃO','VISAR','VISOR','VISTA','VISTO',
  'VITAL','VIÚVA','VIVER','VOGAL','VOLTA','VOSSO','VOTAR',
  // X Z
  'XAMPU','XEQUE','ZEBRA','ZELAR','ZUMBI',
];
