#!/usr/bin/env node
/**
 * Emits packages/core/src/words.generated.ts from two committed inputs:
 *
 *   scripts/dict-merged.txt   — the guess-validation dictionary
 *   packages/core/src/answers.ts — the curated answer pool
 *
 * How dict-merged.txt was produced (kept here so it can be rebuilt):
 *   - lemma list  : github.com/pythonprobr/palavras (palavras.txt)
 *   - inflections : github.com/hermitdave/FrequencyWords 2018/pt_br full,
 *                   5-letter entries with frequency >= 20
 *   The lemma list alone rejects TINHA, PODIA, POSSO and every other conjugated
 *   form, which is unacceptable mid-round. Validation is deliberately generous
 *   — wrongly accepting a rare word costs nothing, wrongly rejecting a real one
 *   costs the player the round.
 *
 * Invariant enforced below: every answer is also a legal guess.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const normalize = (w) =>
  w.normalize('NFD').replace(/[̀-ͯ]/g, '').toUpperCase().replace(/[^A-Z]/g, '');

const dict = new Set(
  readFileSync(join(root, 'scripts/dict-merged.txt'), 'utf8')
    .split('\n').map((l) => normalize(l)).filter((w) => w.length === 5),
);

const answersSrc = readFileSync(join(root, 'packages/core/src/answers.ts'), 'utf8');
const answers = [...answersSrc.split('= [')[1].split('];')[0].matchAll(/'([^']+)'/g)].map((m) => m[1]);

let injected = 0;
for (const a of answers) {
  const n = normalize(a);
  if (n.length !== 5) throw new Error(`answer "${a}" does not normalize to 5 letters (got "${n}")`);
  if (!dict.has(n)) { dict.add(n); injected++; }
}
if (new Set(answers).size !== answers.length) throw new Error('duplicate answer in the pool');

const sorted = [...dict].sort();
const packed = sorted.join('');
if (packed.length !== sorted.length * 5) throw new Error('packed length mismatch');

const chunk = (s) => s.replace(/(.{120})/g, "$1' +\n  '");
writeFileSync(
  join(root, 'packages/core/src/words.generated.ts'),
  `// GENERATED by scripts/build-words.mjs — do not edit by hand.
// ${sorted.length} five-letter pt-BR words packed as contiguous 5-char slices.
export const DICT_COUNT = ${sorted.length};
export const DICT_PACKED =
  '${chunk(packed)}';
`,
);

console.log(`dicionário: ${sorted.length} palavras (${(packed.length / 1024).toFixed(0)} KB cru)`);
console.log(`respostas : ${answers.length} curadas, ${injected} injetadas no dicionário`);
